version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "pyhton manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_ADMIN_USER}
      - DB_PASSWORD=${DATABASE_ADMIN_PASSWD}
    depends_on:
      - "db"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_ADMIN_USER}
      - POSTGRES_PASSWORD=${DATABASE_ADMIN_PASSWD}